# A sample Gemfile
source 'https://rubygems.org'

ruby '2.2.1'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-assetpack'
gem 'sinatra-static-assets'
gem 'sinatra-flash'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'sinatra-param', require: 'sinatra/param'
gem 'oauth'
gem 'twitter'